#!/usr/bin/env python3
"""Generate Claude Code agent files from the canonical Delphi routing contract."""

from __future__ import annotations

import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
CONTRACT_PATH = REPO_ROOT / "config" / "agent_role_routing.json"
CLAUDE_AGENTS_DIR = REPO_ROOT / ".claude" / "agents"
GENERATED_WARNING = (
    "<!-- Generated by tools/sync_claude_agent_routing.py from config/agent_role_routing.json. -->"
)


def load_contract() -> dict:
    return json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))


def frontmatter_block(fields: dict[str, object]) -> str:
    lines = ["---"]
    for key, value in fields.items():
        if isinstance(value, list):
            lines.append(f"{key}:")
            for item in value:
                lines.append(f"  - {item}")
            continue
        lines.append(f"{key}: {value}")
    lines.append("---")
    return "\n".join(lines)


def agent_body(name: str, model: str, effort: str, tools: list[str], prompt: str, description: str) -> str:
    fields = {
        "name": name,
        "description": description,
        "tools": tools,
        "model": model,
        "effort": effort,
    }
    return (
        f"{GENERATED_WARNING}\n"
        f"{frontmatter_block(fields)}\n"
        f"{prompt.strip()}\n"
    )


def build_agents(contract: dict) -> dict[str, str]:
    claude = contract["clients"]["claude-code"]["preferred_models"]
    routine_model = claude["routine_executor"][0]
    review_model = claude["strongest_review"][0]
    monitoring_model = claude["monitoring"][0]

    return {
        "delphi-routine-executor.md": agent_body(
            name="delphi-routine-executor",
            description="Implements already-approved Delphi TODO slices, file edits, and implementation-side validation after routing preflight selects the routine executor lane.",
            tools=["Read", "Grep", "Glob", "Bash", "Edit", "MultiEdit", "Write"],
            model=routine_model,
            effort="medium",
            prompt="""
You are Delphi's routine executor lane.

Accept only bounded implementation or implementation-validation work that was already approved and routed to the executor lane.
Do not take ownership of approval, final adjudication, or broad strategic review.
Keep state compact and local to the current TODO: owned files, decisions, commands/tests, blockers, and last accepted patch state.
Escalate back to the orchestrator when the task needs contract changes, renewed approval, or strong-review adjudication.
""",
        ),
        "delphi-formal-reviewer.md": agent_body(
            name="delphi-formal-reviewer",
            description="Runs Delphi formal review, critique, TODO approval scrutiny, delivery review, and other strongest-review judgment passes.",
            tools=["Read", "Grep", "Glob", "Bash"],
            model=review_model,
            effort="xhigh",
            prompt="""
You are Delphi's formal review lane.

Operate as a stateless no-context reviewer unless the bounded package explicitly requires resumable reviewer state.
Focus on correctness, scope adherence, risk, validation quality, and policy coherence.
Do not write production code or absorb routine implementation work.
Return clear findings, waivers, or clean verdicts that the orchestrator can adjudicate.
""",
        ),
        "delphi-process-monitor.md": agent_body(
            name="delphi-process-monitor",
            description="Runs bounded status passes over logs or background process output when deterministic monitoring alone is insufficient.",
            tools=["Read", "Grep", "Glob", "Bash"],
            model=monitoring_model,
            effort="medium",
            prompt="""
You are Delphi's bounded monitoring lane.

Prefer deterministic status checks first. When an LLM summary is needed, keep it short, bounded, and ephemeral.
Do not become a standing watcher, and do not flood the main conversation with raw logs.
Escalate only the minimum actionable status, blockers, or completion signal.
""",
        ),
    }


def sync_agents() -> int:
    contract = load_contract()
    agents = build_agents(contract)
    CLAUDE_AGENTS_DIR.mkdir(parents=True, exist_ok=True)

    for path in CLAUDE_AGENTS_DIR.glob("*.md"):
        if path.name not in agents:
            path.unlink()

    for filename, content in agents.items():
        target = CLAUDE_AGENTS_DIR / filename
        target.write_text(content, encoding="utf-8")

    print(f"Synchronized {len(agents)} Claude routing agent(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(sync_agents())
