#!/usr/bin/env bash
# verify_package_registry.sh — Scans packages/ directories, cross-references
# manifests, and generates/updates the local packages YAML at:
#   foundation_documentation/local_packages.yaml
#
# In runtime, agents read TWO files:
#   1. delphi-ai/config/ecosystem_packages.yaml  (global, maintained in PACED)
#   2. foundation_documentation/local_packages.yaml (project, generated by this script)
#
# Usage: bash delphi-ai/tools/verify_package_registry.sh [--project-root <path>]
#
# Authority: paced.core.package-first

set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  bash delphi-ai/tools/verify_package_registry.sh [--project-root <path>]
EOF
}

die() {
  echo "Error: $*" >&2
  exit 1
}

require_value() {
  local option="$1"
  local value="${2-}"
  [[ -n "$value" ]] || die "$option requires a non-empty value."
}

canonicalize_dir() {
  local path="$1"
  (cd "$path" >/dev/null 2>&1 && pwd)
}

trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

yaml_quote() {
  local value="$1"
  local escaped

  value="${value//$'\r'/ }"
  value="${value//$'\n'/ }"
  escaped="$(printf '%s' "$value" | sed "s/'/''/g")"
  printf "'%s'" "$escaped"
}

readme_oneliner() {
  local readme="$1"
  [[ -f "$readme" ]] || return 0

  awk '
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*$/ { next }
    {
      sub(/^[[:space:]]+/, "", $0)
      print substr($0, 1, 80)
      exit
    }
  ' "$readme"
}

flutter_package_in_use() {
  local manifest="$1"
  local package_name="$2"

  [[ -f "$manifest" ]] || return 1

  awk -v package_name="$package_name" '
    /^[^[:space:]#][^:]*:[[:space:]]*$/ {
      in_dependencies = ($0 ~ /^(dependencies|dev_dependencies|dependency_overrides):[[:space:]]*$/)
      next
    }

    in_dependencies && $0 ~ /^[[:space:]]+/ {
      if ($0 ~ ("^[[:space:]]+" package_name ":[[:space:]]*($|#)")) {
        found = 1
        exit
      }
      next
    }

    /^[^[:space:]#]/ { in_dependencies = 0 }

    END { exit found ? 0 : 1 }
  ' "$manifest"
}

laravel_package_in_use() {
  local manifest="$1"
  local package_name="$2"

  [[ -f "$manifest" ]] || return 1

  grep -qE "\"${package_name}\"[[:space:]]*:" "$manifest"
}

write_package_entry() {
  local name="$1"
  local path="$2"
  local in_use="$3"
  local has_readme="$4"
  local description="$5"

  cat >> "$LOCAL_YAML" <<EOF
  - name: $(yaml_quote "$name")
    path: $(yaml_quote "$path")
    in_use: $in_use
    has_readme: $has_readme
    description: $(yaml_quote "$description")
EOF
}

validate_project_root() {
  [[ -d "$PROJECT_ROOT" ]] || die "Project root '$PROJECT_ROOT' does not exist or is not a directory."

  PROJECT_ROOT="$(canonicalize_dir "$PROJECT_ROOT")" || die "Unable to resolve project root '$PROJECT_ROOT'."

  [[ -d "$PROJECT_ROOT/delphi-ai" ]] || die "Invalid project root '$PROJECT_ROOT': missing delphi-ai/."
  [[ -d "$PROJECT_ROOT/foundation_documentation" ]] || die "Invalid project root '$PROJECT_ROOT': missing foundation_documentation/."
}

# --- Argument parsing ---
PROJECT_ROOT="."
while [[ $# -gt 0 ]]; do
  case "$1" in
    --help|-h)
      usage
      exit 0
      ;;
    --project-root)
      require_value "--project-root" "${2-}"
      PROJECT_ROOT="$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    -*)
      die "Unknown option '$1'. Use --help for usage."
      ;;
    *)
      PROJECT_ROOT="$1"
      shift
      ;;
  esac
done

if [[ $# -gt 0 ]]; then
  die "Unexpected extra arguments: $*"
fi

validate_project_root

DELPHI_DIR="$PROJECT_ROOT/delphi-ai"
ECOSYSTEM_YAML="$DELPHI_DIR/config/ecosystem_packages.yaml"
LOCAL_YAML="$PROJECT_ROOT/foundation_documentation/local_packages.yaml"
ERRORS=0
WARNINGS=0

echo "=== Package Registry Verification ==="
echo "Project root:     $PROJECT_ROOT"
echo "Ecosystem YAML:   $ECOSYSTEM_YAML"
echo "Local YAML:       $LOCAL_YAML"
echo ""

if [[ ! -f "$ECOSYSTEM_YAML" ]]; then
  echo "WARNING: Ecosystem YAML not found at $ECOSYSTEM_YAML"
  WARNINGS=$((WARNINGS + 1))
fi

# --- Detect stack type and roots ---
HAS_FLUTTER=false
HAS_LARAVEL=false
FLUTTER_ROOT="$PROJECT_ROOT"
LARAVEL_ROOT="$PROJECT_ROOT"

[[ -f "$PROJECT_ROOT/pubspec.yaml" ]] && HAS_FLUTTER=true
[[ -f "$PROJECT_ROOT/composer.json" ]] && HAS_LARAVEL=true

if [[ -d "$PROJECT_ROOT/flutter-app" ]] && [[ -f "$PROJECT_ROOT/flutter-app/pubspec.yaml" ]]; then
  HAS_FLUTTER=true
  FLUTTER_ROOT="$PROJECT_ROOT/flutter-app"
fi
if [[ -d "$PROJECT_ROOT/laravel-app" ]] && [[ -f "$PROJECT_ROOT/laravel-app/composer.json" ]]; then
  HAS_LARAVEL=true
  LARAVEL_ROOT="$PROJECT_ROOT/laravel-app"
fi

# --- Generate local_packages.yaml ---
generate_local_yaml() {
  local timestamp
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  mkdir -p "$(dirname "$LOCAL_YAML")"

  cat > "$LOCAL_YAML" <<EOF
# Local Proprietary Packages
# Auto-generated by delphi-ai/tools/verify_package_registry.sh
# DO NOT edit manually — re-run the script to update.
#
# Agents read this file + delphi-ai/config/ecosystem_packages.yaml
# to determine available proprietary capabilities before implementing.

last_updated: $(yaml_quote "$timestamp")

EOF

  echo "laravel:" >> "$LOCAL_YAML"
  if $HAS_LARAVEL && [[ -d "$LARAVEL_ROOT/packages" ]]; then
    local found=false
    local vendor_dir vendor pkg_dir pkg rel_path readme desc has_readme in_use package_name

    while IFS= read -r -d '' vendor_dir; do
      vendor="$(basename "$vendor_dir")"

      while IFS= read -r -d '' pkg_dir; do
        pkg="$(basename "$pkg_dir")"
        rel_path="packages/$vendor/$pkg"
        readme="$pkg_dir/README.md"
        desc="$(trim "$(readme_oneliner "$readme")")"
        has_readme=true
        in_use=false
        package_name="$vendor/$pkg"

        if [[ ! -f "$readme" ]]; then
          has_readme=false
          WARNINGS=$((WARNINGS + 1))
          echo "  WARNING: $rel_path missing README.md"
        fi

        if laravel_package_in_use "$LARAVEL_ROOT/composer.json" "$package_name"; then
          in_use=true
        fi

        write_package_entry "$package_name" "$rel_path" "$in_use" "$has_readme" "$desc"
        found=true
      done < <(find "$vendor_dir" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)
    done < <(find "$LARAVEL_ROOT/packages" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

    if ! $found; then
      echo "  []  # No local Laravel packages found" >> "$LOCAL_YAML"
    fi
  else
    echo "  []  # No Laravel packages/ directory detected" >> "$LOCAL_YAML"
  fi

  echo "" >> "$LOCAL_YAML"

  echo "flutter:" >> "$LOCAL_YAML"
  if $HAS_FLUTTER && [[ -d "$FLUTTER_ROOT/packages" ]]; then
    local found=false
    local pkg_dir pkg rel_path readme desc has_readme in_use

    while IFS= read -r -d '' pkg_dir; do
      [[ -f "$pkg_dir/pubspec.yaml" ]] || continue

      pkg="$(basename "$pkg_dir")"
      rel_path="packages/$pkg"
      readme="$pkg_dir/README.md"
      desc="$(trim "$(readme_oneliner "$readme")")"
      has_readme=true
      in_use=false

      if [[ ! -f "$readme" ]]; then
        has_readme=false
        WARNINGS=$((WARNINGS + 1))
        echo "  WARNING: $rel_path missing README.md"
      fi

      if flutter_package_in_use "$FLUTTER_ROOT/pubspec.yaml" "$pkg"; then
        in_use=true
      fi

      write_package_entry "$pkg" "$rel_path" "$in_use" "$has_readme" "$desc"
      found=true
    done < <(find "$FLUTTER_ROOT/packages" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

    if ! $found; then
      echo "  []  # No local Flutter packages found" >> "$LOCAL_YAML"
    fi
  else
    echo "  []  # No Flutter packages/ directory detected" >> "$LOCAL_YAML"
  fi

  echo "" >> "$LOCAL_YAML"

  echo "anti_patterns:" >> "$LOCAL_YAML"
  local has_antipatterns=false
  local count

  if [[ -d "$LARAVEL_ROOT/app/Helpers" ]]; then
    count=$(find "$LARAVEL_ROOT/app/Helpers" -name "*.php" 2>/dev/null | wc -l | tr -d '[:space:]')
    if [[ "$count" -gt 0 ]]; then
      cat >> "$LOCAL_YAML" <<EOF
  - location: $(yaml_quote "app/Helpers/")
    count: $count
    action: $(yaml_quote "candidates for package extraction")
EOF
      WARNINGS=$((WARNINGS + count))
      has_antipatterns=true
    fi
  fi

  if [[ -d "$FLUTTER_ROOT/lib/utils" ]]; then
    count=$(find "$FLUTTER_ROOT/lib/utils" -name "*.dart" 2>/dev/null | wc -l | tr -d '[:space:]')
    if [[ "$count" -gt 0 ]]; then
      cat >> "$LOCAL_YAML" <<EOF
  - location: $(yaml_quote "lib/utils/")
    count: $count
    action: $(yaml_quote "candidates for library extraction")
EOF
      WARNINGS=$((WARNINGS + count))
      has_antipatterns=true
    fi
  fi

  if ! $has_antipatterns; then
    echo "  []  # No anti-patterns detected" >> "$LOCAL_YAML"
  fi

  echo "" >> "$LOCAL_YAML"
  echo "Local YAML written to: $LOCAL_YAML"
}

generate_local_yaml

echo ""
echo "=== Summary ==="
echo "Errors:   $ERRORS"
echo "Warnings: $WARNINGS"

if [[ "$ERRORS" -gt 0 ]]; then
  echo "STATUS: FAIL"
  exit 1
elif [[ "$WARNINGS" -gt 0 ]]; then
  echo "STATUS: PASS WITH WARNINGS"
  exit 0
else
  echo "STATUS: PASS"
  exit 0
fi
