#!/usr/bin/env bash
# verify_package_registry.sh — Scans packages/ directories, cross-references
# manifests, and generates/updates the local packages YAML at:
#   foundation_documentation/local_packages.yaml
#
# In runtime, agents read TWO files:
#   1. delphi-ai/config/ecosystem_packages.yaml  (global, maintained in PACED)
#   2. foundation_documentation/local_packages.yaml (project, generated by this script)
#
# Usage: bash delphi-ai/tools/verify_package_registry.sh [--project-root <path>]
#
# Authority: paced.core.package-first

set -euo pipefail

# --- Argument parsing ---
PROJECT_ROOT="."
while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-root) PROJECT_ROOT="$2"; shift 2 ;;
    *) PROJECT_ROOT="$1"; shift ;;
  esac
done

DELPHI_DIR="$PROJECT_ROOT/delphi-ai"
ECOSYSTEM_YAML="$DELPHI_DIR/config/ecosystem_packages.yaml"
LOCAL_YAML="$PROJECT_ROOT/foundation_documentation/local_packages.yaml"
ERRORS=0
WARNINGS=0

echo "=== Package Registry Verification ==="
echo "Project root:     $PROJECT_ROOT"
echo "Ecosystem YAML:   $ECOSYSTEM_YAML"
echo "Local YAML:       $LOCAL_YAML"
echo ""

# --- Validate ecosystem YAML ---
if [[ ! -f "$ECOSYSTEM_YAML" ]]; then
  echo "WARNING: Ecosystem YAML not found at $ECOSYSTEM_YAML"
  WARNINGS=$((WARNINGS + 1))
fi

# --- Detect stack type and roots ---
HAS_FLUTTER=false
HAS_LARAVEL=false
FLUTTER_ROOT="$PROJECT_ROOT"
LARAVEL_ROOT="$PROJECT_ROOT"

[[ -f "$PROJECT_ROOT/pubspec.yaml" ]] && HAS_FLUTTER=true
[[ -f "$PROJECT_ROOT/composer.json" ]] && HAS_LARAVEL=true

if [[ -d "$PROJECT_ROOT/flutter-app" ]] && [[ -f "$PROJECT_ROOT/flutter-app/pubspec.yaml" ]]; then
  HAS_FLUTTER=true
  FLUTTER_ROOT="$PROJECT_ROOT/flutter-app"
fi
if [[ -d "$PROJECT_ROOT/laravel-app" ]] && [[ -f "$PROJECT_ROOT/laravel-app/composer.json" ]]; then
  HAS_LARAVEL=true
  LARAVEL_ROOT="$PROJECT_ROOT/laravel-app"
fi

# --- Helper: extract first non-header line from README ---
readme_oneliner() {
  local readme="$1"
  if [[ -f "$readme" ]]; then
    sed -n '/^[^#]/p' "$readme" | head -1 | sed 's/^[[:space:]]*//' | cut -c1-80
  else
    echo ""
  fi
}

# --- Generate local_packages.yaml ---
generate_local_yaml() {
  local timestamp
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  mkdir -p "$(dirname "$LOCAL_YAML")"

  cat > "$LOCAL_YAML" << EOF
# Local Proprietary Packages
# Auto-generated by delphi-ai/tools/verify_package_registry.sh
# DO NOT edit manually — re-run the script to update.
#
# Agents read this file + delphi-ai/config/ecosystem_packages.yaml
# to determine available proprietary capabilities before implementing.

last_updated: "$timestamp"

EOF

  # --- Laravel local packages ---
  echo "laravel:" >> "$LOCAL_YAML"
  if $HAS_LARAVEL && [[ -d "$LARAVEL_ROOT/packages" ]]; then
    local found=false
    for vendor_dir in "$LARAVEL_ROOT/packages"/*/; do
      [[ -d "$vendor_dir" ]] || continue
      local vendor
      vendor=$(basename "$vendor_dir")

      for pkg_dir in "$vendor_dir"*/; do
        [[ -d "$pkg_dir" ]] || continue
        local pkg
        pkg=$(basename "$pkg_dir")
        local rel_path="packages/$vendor/$pkg"
        local readme="$pkg_dir/README.md"
        local desc
        desc=$(readme_oneliner "$readme")
        local has_readme=true
        local in_use=false

        if [[ ! -f "$readme" ]]; then
          has_readme=false
          WARNINGS=$((WARNINGS + 1))
          echo "  WARNING: $rel_path missing README.md"
        fi

        if [[ -f "$LARAVEL_ROOT/composer.json" ]] && grep -q "${vendor}/${pkg}\|${vendor}_${pkg}" "$LARAVEL_ROOT/composer.json" 2>/dev/null; then
          in_use=true
        fi

        cat >> "$LOCAL_YAML" << EOF
  - name: "$vendor/$pkg"
    path: "$rel_path"
    in_use: $in_use
    has_readme: $has_readme
    description: "$desc"
EOF
        found=true
      done
    done
    if ! $found; then
      echo "  []  # No local Laravel packages found" >> "$LOCAL_YAML"
    fi
  else
    echo "  []  # No Laravel packages/ directory detected" >> "$LOCAL_YAML"
  fi

  echo "" >> "$LOCAL_YAML"

  # --- Flutter local packages ---
  echo "flutter:" >> "$LOCAL_YAML"
  if $HAS_FLUTTER && [[ -d "$FLUTTER_ROOT/packages" ]]; then
    local found=false
    for pkg_dir in "$FLUTTER_ROOT/packages"/*/; do
      [[ -d "$pkg_dir" ]] || continue
      [[ -f "$pkg_dir/pubspec.yaml" ]] || continue

      local pkg
      pkg=$(basename "$pkg_dir")
      local rel_path="packages/$pkg"
      local readme="$pkg_dir/README.md"
      local desc
      desc=$(readme_oneliner "$readme")
      local has_readme=true
      local in_use=false

      if [[ ! -f "$readme" ]]; then
        has_readme=false
        WARNINGS=$((WARNINGS + 1))
        echo "  WARNING: $rel_path missing README.md"
      fi

      if [[ -f "$FLUTTER_ROOT/pubspec.yaml" ]] && grep -q "$pkg" "$FLUTTER_ROOT/pubspec.yaml" 2>/dev/null; then
        in_use=true
      fi

      cat >> "$LOCAL_YAML" << EOF
  - name: "$pkg"
    path: "$rel_path"
    in_use: $in_use
    has_readme: $has_readme
    description: "$desc"
EOF
      found=true
    done
    if ! $found; then
      echo "  []  # No local Flutter packages found" >> "$LOCAL_YAML"
    fi
  else
    echo "  []  # No Flutter packages/ directory detected" >> "$LOCAL_YAML"
  fi

  echo "" >> "$LOCAL_YAML"

  # --- Anti-pattern watchlist ---
  echo "anti_patterns:" >> "$LOCAL_YAML"
  local has_antipatterns=false

  if [[ -d "$LARAVEL_ROOT/app/Helpers" ]]; then
    local count
    count=$(find "$LARAVEL_ROOT/app/Helpers" -name "*.php" 2>/dev/null | wc -l)
    if [[ "$count" -gt 0 ]]; then
      echo "  - location: \"app/Helpers/\"" >> "$LOCAL_YAML"
      echo "    count: $count" >> "$LOCAL_YAML"
      echo "    action: \"candidates for package extraction\"" >> "$LOCAL_YAML"
      WARNINGS=$((WARNINGS + count))
      has_antipatterns=true
    fi
  fi

  if [[ -d "$FLUTTER_ROOT/lib/utils" ]]; then
    local count
    count=$(find "$FLUTTER_ROOT/lib/utils" -name "*.dart" 2>/dev/null | wc -l)
    if [[ "$count" -gt 0 ]]; then
      echo "  - location: \"lib/utils/\"" >> "$LOCAL_YAML"
      echo "    count: $count" >> "$LOCAL_YAML"
      echo "    action: \"candidates for library extraction\"" >> "$LOCAL_YAML"
      WARNINGS=$((WARNINGS + count))
      has_antipatterns=true
    fi
  fi

  if ! $has_antipatterns; then
    echo "  []  # No anti-patterns detected" >> "$LOCAL_YAML"
  fi

  echo "" >> "$LOCAL_YAML"
  echo "Local YAML written to: $LOCAL_YAML"
}

# --- Run ---
generate_local_yaml

# --- Summary ---
echo ""
echo "=== Summary ==="
echo "Errors:   $ERRORS"
echo "Warnings: $WARNINGS"

if [[ "$ERRORS" -gt 0 ]]; then
  echo "STATUS: FAIL"
  exit 1
elif [[ "$WARNINGS" -gt 0 ]]; then
  echo "STATUS: PASS WITH WARNINGS"
  exit 0
else
  echo "STATUS: PASS"
  exit 0
fi
